version: "3.8"

services:
  sonarqube:
    image: sonarqube:8.8-community
    ulimits:
      nproc: 65535
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sonarqube

networks:
    sonarqube:
        name: sonarqube
